/* ════════════════════════════════════════
   Slash – Language Translations
   ════════════════════════════════════════ */

const LANGS = {
  de: {
    dir: 'ltr',
    eyebrowNav: 'IPv4 Subnetzrechner',
    heroEyebrow: 'Subnetzrechner',
    heroTitleMain: 'Gib eine Adresse ein.',
    heroSpan: 'Er rechnet den Rest.',
    heroSub: 'Adresse und Präfixlänge eingeben — Slash berechnet sofort Netzwerk-, Broadcast- und Hostbereich und zeigt genau, welche Bits welche Aufgabe haben.',
    ipLabel: 'IP-Adresse',
    prefixLabel: 'Präfix',
    errorMsg: 'Gib eine gültige IPv4-Adresse ein, z. B. 192.168.1.0',
    bitsHeading: 'Welche Bits sind Netz, welche sind Host',
    legendNetwork: 'Netz',
    legendHost: 'Host',
    cidrReadout: (v, total) => `/${v} · ${total} Adressen`,
    binShow: 'Binärrechnung anzeigen ▾',
    binHide: 'Binärrechnung ausblenden ▴',
    resultsHeading: 'Ergebnis',
    res: { network: 'Netzwerkadresse', broadcast: 'Broadcast-Adresse', firstHost: 'Erster nutzbarer Host', lastHost: 'Letzter nutzbarer Host', total: 'Adressen gesamt', usable: 'Nutzbare Hosts', mask: 'Subnetzmaske', wildcard: 'Wildcard-Maske', ipClass: 'IP-Klasse', addrType: 'Adresstyp' },
    copyLabel: 'kopieren',
    toastCopied: 'Kopiert',
    splitterHeading: 'Dieses Netz aufteilen',
    splitterDesc: 'Teile das obige Netz in kleinere, gleich große Subnetze auf.',
    splitByLabel: 'Aufteilen nach',
    splitModeCount: 'Anzahl Subnetze',
    splitModeHosts: 'Hosts pro Subnetz',
    splitValueLabel: 'Wert',
    splitBtnLabel: 'Netz aufteilen',
    splitWarnCant: (cidr) => `Aufteilung nicht möglich — die gewünschte Größe passt nicht in ein /${cidr}-Netz.`,
    splitWarnShowing: (cap, total) => `Zeigt die ersten ${cap} von ${total} Subnetzen.`,
    th: { subnet: 'Subnetz', network: 'Netzwerk', firstHost: 'Erster Host', lastHost: 'Letzter Host', broadcast: 'Broadcast', mask: 'Maske' },
    footerText: 'Läuft vollständig im Browser. Nichts wird an einen Server gesendet.',
    bitTooltip: (bit, prefix) => `Bit ${bit} — klicken, um das Präfix auf /${prefix} zu setzen`,
    addr: { public: 'Öffentlich', private: 'Privat (RFC 1918)', loopback: 'Loopback', linkLocal: 'Link-lokal' },
    classSuffix: { multicast: ' (Multicast)', reserved: ' (reserviert)' },
    p2pSuffix: '2 (RFC 3021 Punkt-zu-Punkt)',
  },
  en: {
    dir: 'ltr',
    eyebrowNav: 'IPv4 subnet calculator',
    heroEyebrow: 'Subnet calculator',
    heroTitleMain: 'Give it an address.',
    heroSpan: 'It does the math.',
    heroSub: 'Type an IP and a prefix length — Slash works out the network, broadcast, and usable host range instantly, and shows exactly which bits are doing the work.',
    ipLabel: 'IP address',
    prefixLabel: 'Prefix',
    errorMsg: 'Enter a valid IPv4 address, e.g. 192.168.1.0',
    bitsHeading: 'Which bits are network, which are host',
    legendNetwork: 'Network',
    legendHost: 'Host',
    cidrReadout: (v, total) => `/${v} · ${total} addresses`,
    binShow: 'Show the binary math ▾',
    binHide: 'Hide the binary math ▴',
    resultsHeading: 'Result',
    res: { network: 'Network address', broadcast: 'Broadcast address', firstHost: 'First usable host', lastHost: 'Last usable host', total: 'Total addresses', usable: 'Usable hosts', mask: 'Subnet mask', wildcard: 'Wildcard mask', ipClass: 'IP class', addrType: 'Address type' },
    copyLabel: 'copy',
    toastCopied: 'Copied',
    splitterHeading: 'Split this network',
    splitterDesc: 'Break the network above into smaller, equal-sized subnets.',
    splitByLabel: 'Split by',
    splitModeCount: 'Number of subnets',
    splitModeHosts: 'Hosts per subnet',
    splitValueLabel: 'Value',
    splitBtnLabel: 'Split network',
    splitWarnCant: (cidr) => `Can't split — the requested size doesn't fit inside a /${cidr} network.`,
    splitWarnShowing: (cap, total) => `Showing the first ${cap} of ${total} subnets.`,
    th: { subnet: 'Subnet', network: 'Network', firstHost: 'First host', lastHost: 'Last host', broadcast: 'Broadcast', mask: 'Mask' },
    footerText: 'Runs entirely in your browser. Nothing you type here is sent anywhere.',
    bitTooltip: (bit, prefix) => `Bit ${bit} — click to set prefix to /${prefix}`,
    addr: { public: 'Public', private: 'Private (RFC 1918)', loopback: 'Loopback', linkLocal: 'Link-local' },
    classSuffix: { multicast: ' (multicast)', reserved: ' (reserved)' },
    p2pSuffix: '2 (RFC 3021 point-to-point)',
  },
  ar: {
    dir: 'rtl',
    eyebrowNav: 'حاسبة الشبكات الفرعية IPv4',
    heroEyebrow: 'حاسبة الشبكات الفرعية',
    heroTitleMain: 'أدخل عنوانًا.',
    heroSpan: 'وسيقوم بالحساب.',
    heroSub: 'أدخل عنوان IP وطول البادئة — يحسب Slash فورًا عنوان الشبكة والبث والنطاق المتاح للمضيفين، ويوضح بالضبط أي البتات تقوم بالعمل.',
    ipLabel: 'عنوان IP',
    prefixLabel: 'البادئة',
    errorMsg: 'أدخل عنوان IPv4 صالحًا، مثل 192.168.1.0',
    bitsHeading: 'ما هي بتات الشبكة وما هي بتات المضيف',
    legendNetwork: 'الشبكة',
    legendHost: 'المضيف',
    cidrReadout: (v, total) => `/${v} · ${total} عنوان`,
    binShow: 'إظهار الحساب الثنائي ▾',
    binHide: 'إخفاء الحساب الثنائي ▴',
    resultsHeading: 'النتيجة',
    res: { network: 'عنوان الشبكة', broadcast: 'عنوان البث', firstHost: 'أول مضيف صالح', lastHost: 'آخر مضيف صالح', total: 'إجمالي العناوين', usable: 'المضيفون القابلون للاستخدام', mask: 'قناع الشبكة الفرعية', wildcard: 'قناع Wildcard', ipClass: 'فئة IP', addrType: 'نوع العنوان' },
    copyLabel: 'نسخ',
    toastCopied: 'تم النسخ',
    splitterHeading: 'تقسيم هذه الشبكة',
    splitterDesc: 'قسّم الشبكة أعلاه إلى شبكات فرعية أصغر ومتساوية الحجم.',
    splitByLabel: 'التقسيم حسب',
    splitModeCount: 'عدد الشبكات الفرعية',
    splitModeHosts: 'المضيفون لكل شبكة فرعية',
    splitValueLabel: 'القيمة',
    splitBtnLabel: 'تقسيم الشبكة',
    splitWarnCant: (cidr) => `تعذر التقسيم — الحجم المطلوب لا يناسب شبكة /${cidr}.`,
    splitWarnShowing: (cap, total) => `عرض أول ${cap} من أصل ${total} شبكة فرعية.`,
    th: { subnet: 'شبكة فرعية', network: 'الشبكة', firstHost: 'أول مضيف', lastHost: 'آخر مضيف', broadcast: 'البث', mask: 'القناع' },
    footerText: 'يعمل بالكامل في متصفحك. لا يتم إرسال أي شيء تكتبه إلى أي مكان.',
    bitTooltip: (bit, prefix) => `البت ${bit} — انقر لتعيين البادئة إلى /${prefix}`,
    addr: { public: 'عام', private: 'خاص (RFC 1918)', loopback: 'Loopback', linkLocal: 'رابط محلي' },
    classSuffix: { multicast: ' (بث متعدد)', reserved: ' (محجوز)' },
    p2pSuffix: '2 (RFC 3021 نقطة إلى نقطة)',
  },
  tr: {
    dir: 'ltr',
    eyebrowNav: 'IPv4 alt ağ hesaplayıcı',
    heroEyebrow: 'Alt ağ hesaplayıcı',
    heroTitleMain: 'Bir adres ver.',
    heroSpan: 'Hesabı o yapsın.',
    heroSub: 'Bir IP ve önek uzunluğu gir — Slash ağ, yayın ve kullanılabilir host aralığını anında hesaplar ve hangi bitlerin ne iş yaptığını gösterir.',
    ipLabel: 'IP adresi',
    prefixLabel: 'Önek',
    errorMsg: 'Geçerli bir IPv4 adresi girin, örn. 192.168.1.0',
    bitsHeading: 'Hangi bitler ağ, hangileri host',
    legendNetwork: 'Ağ',
    legendHost: 'Host',
    cidrReadout: (v, total) => `/${v} · ${total} adres`,
    binShow: 'İkili hesaplamayı göster ▾',
    binHide: 'İkili hesaplamayı gizle ▴',
    resultsHeading: 'Sonuç',
    res: { network: 'Ağ adresi', broadcast: 'Yayın adresi', firstHost: 'İlk kullanılabilir host', lastHost: 'Son kullanılabilir host', total: 'Toplam adres', usable: 'Kullanılabilir hostlar', mask: 'Alt ağ maskesi', wildcard: 'Wildcard maskesi', ipClass: 'IP sınıfı', addrType: 'Adres türü' },
    copyLabel: 'kopyala',
    toastCopied: 'Kopyalandı',
    splitterHeading: 'Bu ağı böl',
    splitterDesc: 'Yukarıdaki ağı daha küçük, eşit boyutlu alt ağlara böl.',
    splitByLabel: 'Bölme şekli',
    splitModeCount: 'Alt ağ sayısı',
    splitModeHosts: 'Alt ağ başına host',
    splitValueLabel: 'Değer',
    splitBtnLabel: 'Ağı böl',
    splitWarnCant: (cidr) => `Bölünemiyor — istenen boyut bir /${cidr} ağına sığmıyor.`,
    splitWarnShowing: (cap, total) => `${total} alt ağdan ilk ${cap} tanesi gösteriliyor.`,
    th: { subnet: 'Alt ağ', network: 'Ağ', firstHost: 'İlk host', lastHost: 'Son host', broadcast: 'Yayın', mask: 'Maske' },
    footerText: 'Tamamen tarayıcınızda çalışır. Buraya yazdığınız hiçbir şey herhangi bir yere gönderilmez.',
    bitTooltip: (bit, prefix) => `Bit ${bit} — öneki /${prefix} yapmak için tıkla`,
    addr: { public: 'Genel', private: 'Özel (RFC 1918)', loopback: 'Loopback', linkLocal: 'Bağlantı yerel' },
    classSuffix: { multicast: ' (multicast)', reserved: ' (ayrılmış)' },
    p2pSuffix: '2 (RFC 3021 noktadan noktaya)',
  },
  fr: {
    dir: 'ltr',
    eyebrowNav: 'Calculateur de sous-réseau IPv4',
    heroEyebrow: 'Calculateur de sous-réseau',
    heroTitleMain: 'Donne-lui une adresse.',
    heroSpan: 'Il fait le calcul.',
    heroSub: "Saisis une IP et une longueur de préfixe — Slash calcule instantanément le réseau, la diffusion et la plage d'hôtes utilisables, et montre exactement quels bits font le travail.",
    ipLabel: 'Adresse IP',
    prefixLabel: 'Préfixe',
    errorMsg: 'Entrez une adresse IPv4 valide, ex. 192.168.1.0',
    bitsHeading: 'Quels bits sont réseau, lesquels sont hôte',
    legendNetwork: 'Réseau',
    legendHost: 'Hôte',
    cidrReadout: (v, total) => `/${v} · ${total} adresses`,
    binShow: 'Afficher le calcul binaire ▾',
    binHide: 'Masquer le calcul binaire ▴',
    resultsHeading: 'Résultat',
    res: { network: 'Adresse réseau', broadcast: 'Adresse de diffusion', firstHost: 'Premier hôte utilisable', lastHost: 'Dernier hôte utilisable', total: 'Adresses totales', usable: 'Hôtes utilisables', mask: 'Masque de sous-réseau', wildcard: 'Masque générique', ipClass: 'Classe IP', addrType: "Type d'adresse" },
    copyLabel: 'copier',
    toastCopied: 'Copié',
    splitterHeading: 'Diviser ce réseau',
    splitterDesc: 'Découpe le réseau ci-dessus en sous-réseaux plus petits et de taille égale.',
    splitByLabel: 'Diviser par',
    splitModeCount: 'Nombre de sous-réseaux',
    splitModeHosts: 'Hôtes par sous-réseau',
    splitValueLabel: 'Valeur',
    splitBtnLabel: 'Diviser le réseau',
    splitWarnCant: (cidr) => `Division impossible — la taille demandée ne tient pas dans un réseau /${cidr}.`,
    splitWarnShowing: (cap, total) => `Affichage des ${cap} premiers sous-réseaux sur ${total}.`,
    th: { subnet: 'Sous-réseau', network: 'Réseau', firstHost: 'Premier hôte', lastHost: 'Dernier hôte', broadcast: 'Diffusion', mask: 'Masque' },
    footerText: "Fonctionne entièrement dans votre navigateur. Rien de ce que vous tapez ici n'est envoyé où que ce soit.",
    bitTooltip: (bit, prefix) => `Bit ${bit} — cliquez pour régler le préfixe sur /${prefix}`,
    addr: { public: 'Public', private: 'Privé (RFC 1918)', loopback: 'Bouclage', linkLocal: 'Lien local' },
    classSuffix: { multicast: ' (multidiffusion)', reserved: ' (réservée)' },
    p2pSuffix: '2 (RFC 3021 point-à-point)',
  },
  es: {
    dir: 'ltr',
    eyebrowNav: 'Calculadora de subred IPv4',
    heroEyebrow: 'Calculadora de subred',
    heroTitleMain: 'Dale una dirección.',
    heroSpan: 'Él hace el cálculo.',
    heroSub: 'Escribe una IP y una longitud de prefijo — Slash calcula al instante la red, la difusión y el rango de hosts utilizables, y muestra exactamente qué bits hacen el trabajo.',
    ipLabel: 'Dirección IP',
    prefixLabel: 'Prefijo',
    errorMsg: 'Introduce una dirección IPv4 válida, p. ej. 192.168.1.0',
    bitsHeading: 'Qué bits son de red y cuáles de host',
    legendNetwork: 'Red',
    legendHost: 'Host',
    cidrReadout: (v, total) => `/${v} · ${total} direcciones`,
    binShow: 'Mostrar el cálculo binario ▾',
    binHide: 'Ocultar el cálculo binario ▴',
    resultsHeading: 'Resultado',
    res: { network: 'Dirección de red', broadcast: 'Dirección de difusión', firstHost: 'Primer host utilizable', lastHost: 'Último host utilizable', total: 'Direcciones totales', usable: 'Hosts utilizables', mask: 'Máscara de subred', wildcard: 'Máscara wildcard', ipClass: 'Clase IP', addrType: 'Tipo de dirección' },
    copyLabel: 'copiar',
    toastCopied: 'Copiado',
    splitterHeading: 'Dividir esta red',
    splitterDesc: 'Divide la red anterior en subredes más pequeñas y de igual tamaño.',
    splitByLabel: 'Dividir por',
    splitModeCount: 'Número de subredes',
    splitModeHosts: 'Hosts por subred',
    splitValueLabel: 'Valor',
    splitBtnLabel: 'Dividir red',
    splitWarnCant: (cidr) => `No se puede dividir — el tamaño solicitado no cabe en una red /${cidr}.`,
    splitWarnShowing: (cap, total) => `Mostrando las primeras ${cap} de ${total} subredes.`,
    th: { subnet: 'Subred', network: 'Red', firstHost: 'Primer host', lastHost: 'Último host', broadcast: 'Difusión', mask: 'Máscara' },
    footerText: 'Funciona completamente en tu navegador. Nada de lo que escribas aquí se envía a ningún sitio.',
    bitTooltip: (bit, prefix) => `Bit ${bit} — haz clic para fijar el prefijo en /${prefix}`,
    addr: { public: 'Pública', private: 'Privada (RFC 1918)', loopback: 'Loopback', linkLocal: 'Enlace local' },
    classSuffix: { multicast: ' (multidifusión)', reserved: ' (reservada)' },
    p2pSuffix: '2 (RFC 3021 punto a punto)',
  },
};

let currentLang = localStorage.getItem('slash-lang') || 'en';

function getLang() {
  return LANGS[currentLang] || LANGS['en'];
}

function setLang(lang, callback) {
  currentLang = LANGS[lang] ? lang : 'en';
  localStorage.setItem('slash-lang', currentLang);
  const L = LANGS[currentLang];
  document.documentElement.lang = currentLang;
  document.body.setAttribute('dir', L.dir);
  if (callback) callback();
}
